# Generated by Django 3.2.9 on 2021-11-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpuUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.IntegerField()),
                ('sys_usage', models.FloatField()),
                ('user_usage', models.FloatField()),
                ('idle', models.FloatField()),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
