# Generated by Django 3.2.9 on 2021-11-20 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cpumonitor', '0002_remove_cpuusage_create_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpuusage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
