# Generated by Django 3.2.9 on 2021-11-22 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpumonitor', '0003_cpuusage_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpuusage',
            old_name='idle',
            new_name='idle_usage_percentage',
        ),
        migrations.RenameField(
            model_name='cpuusage',
            old_name='sys_usage',
            new_name='sys_usage_percentage',
        ),
        migrations.RenameField(
            model_name='cpuusage',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='cpuusage',
            old_name='user_usage',
            new_name='user_usage_percentage',
        ),
    ]
